name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - actions

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20', '22', '24']
    steps:
    - uses: actions/checkout@v4
      name: Repository checkout
    - uses: actions/setup-node@v4
      name: Node ${{ matrix.node-version }} Setup
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build and test
      run: npm test
